# TODO: ensure that the git package is installed

- name: Deploy Gitlab repository content directly to remote machine
  git:
    repo: "https://{{ gitlabartifact_deploytoken_name }}:{{ gitlabartifact_deploytoken_content }}@{{ gitlabartifact_server }}/{{ gitlabartifact_project_id }}.git"
    dest: "{{ gitlabartifact_remote_destination }}"
    version: "{{ gitlabartifact_git_reference }}"
    depth: "{{ gitlabartifact_clonedepth }}"
    force: "{{ gitlabartifact_overwrite }}"
  notify:
  - restart services
