- name: Use standard indirect artifact deployment
  import_tasks: artifact.yml
  when: not (gitlabartifact_deploytoken_number is defined)
- name: Use direct Git deployment
  import_tasks: git.yml
  when: gitlabartifact_deploytoken_number is defined
